samples: samples.tsv
units: units.tsv

ref:
  name: GK18
  # path to the reference genome
  genome: data/ref/gk18.fa
  # path to GTF annotation file 
  annotation: data/ref/gk18.gtf  
  
# path to adapter sequences file
adapters: data/ref/adapters.fa


params:
  picard:
    MarkDuplicates: "REMOVE_DUPLICATES=true"
  trimmomatic:
    options:
      - "LEADING:3"
      - "TRAILING:3"
      - "MINLEN:50"
      - "AVGQUAL:30"
      - "-phred33"
    clip:
      - "ILLUMINACLIP:{}:2:30:10" 
    threads: 8
      
      
   
        
      
