samples: samples.tsv

# TODO Add directory to store data

ref:
  name: GK18
  # name of directory with reference files
  dir: ref/
  # path to the reference genome
  genome: ref/gk18.fa
  # path to GTF annotation file 
  annotation: ref/gk18.gtf  
  
# path to adapter sequences file
adapters: adapters.fa
       
# number of threads to use
threads: 8

spades:
  # enter either illumina or iontorrent for sequencer platform
  platform: illumina
  # k-mer sizes must be odd, less than 128, and listed in ascending order 
  #kmer_sizes: 21,33,55 
  kmer_sizes: 
 
