samples: samples.tsv
units: units.tsv

ref:
  name: GK18
  # path to the reference genome
  genome: data/ref/gk18.fa
  # path to GTF annotation file 
  annotation: data/ref/gk18.gtf  
  
# path to adapter file
adapters: data/ref/adapters.fa


params:
  picard:
    MarkDuplicates: "REMOVE_DUPLICATES=true"
  trimmomatic:
    pe:
      trimmer:
        # See trimmomatic manual for adding additional options, e.g. for adapter trimming.
        - "LEADING:3"
        - "TRAILING:3"
        - "SLIDINGWINDOW:4:15"
        - "MINLEN:36"

